### ISSUE TITLE
Live Deployment

### ISSUE THREAD

**Issue by ericvanderwal** [rgab1508/OpenStore#1]
Hi, this looks like a pretty interesting project. I am the head of developer relations at the nervos network blockchain. I was wondering if you have any live deployment of openstore, perhaps running on a testnet I could see? Thank you! ~

**Comment by adiunni** [comment]
Hi. Thank you for your interest in the project. We have currently deployed the project in Polygon Mumbai testnet. However doing this not only slowed down the creation process cascading to slow transactions and resulting in an error in creation (mainly due to network error)

The faucet providing test tokens also returns an error signifying the replacement transaction to be underpriced. Due to this, we were not able to get the tokens necessary to conduct transactions for creation as well as for purchase (We were able to get some tokens for deployment).

Once again, thanks for your interest and will get back to you once we get these sorted out

**Comment by AakashCode12** [comment]
We have created a demo video for the same 
https://www.youtube.com/watch?v=sHytyvUQB0Q
